using UnityEngine;
using UnityEngine.InputSystem;

public class InputHandler : MonoBehaviour
{
    private Vector2 movementInput;
    private bool lockOnPressed;

    private void OnEnable()
    {
        var playerInput = new PlayerInputActions();  // Automatically generated by the Input System
        playerInput.Player.Enable();
        playerInput.Player.Move.performed += ctx => movementInput = ctx.ReadValue<Vector2>();
        playerInput.Player.Move.canceled += ctx => movementInput = Vector2.zero;
        playerInput.Player.ZTarget.performed += ctx => lockOnPressed = true;
        playerInput.Player.ZTarget.canceled += ctx => lockOnPressed = false;
    }

    public Vector3 GetMovementInput()
    {
        return new Vector3(movementInput.x, 0f, movementInput.y);
    }

    public bool GetLockOnInput()
    {
        return lockOnPressed;
    }
}
